# Default values for search-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-gitlab.prozorro.sale/prozorro-sale/{{cookiecutter.project_name}}
  tag: latest
  pullPolicy: Always


imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - host: {{cookiecutter.project_name}}.localhost
      paths:
        - /

resources:
  limits:
    cpu: 1200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

swaggerDoc: 1
