dist: xenial
language: python
sudo: required

services:
  - docker

python:
  - '3.9'

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt

script:
  - make flake
  - make test

before_script:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/postgresql stop

cache: pip

jobs:
  include:
    - &deploy_job
      stage: Upload a new version of python package to PYPI
      name: Publishing current Git tagged version of dist to PyPI
      if: repo == "Kuzmenko-Pavel/Prozorro-Sale-Start-Kit" AND tag IS present
      install: []
      script: skip

      before_deploy:
        - pip install --upgrade pep517
        - python -m pep517.build --source --binary --out-dir dist .
        - echo > setup.py

      deploy: &deploy_step
        provider: pypi
        user: Prozorro-Sale-Start-Kit
        skip-cleanup: true
        password:
          # Encrypted with `travis encrypt -r Kuzmenko-Pavel/Prozorro-Sale-Start-Kit --api-endpoint 'https://api.travis-ci.com/'`:
          secure: "VkidT4OfseeC46KTxjlmZGRljWzFGZKy6UlwWkRpWMDj7Ymz8WpxZbs0LgJZRbZSgzh5HZP00NlJTkCCtqvJbAfdAqiMQxwn32CebJFKlwoHm2jooAawiPwVtp1KWtZodsMb17mQurewF9d/g4yPfD+HmlceJCKuNigE2JC0zjJ+nEVHk/fhHHY1PEigT5upKJPliCeFt4mHOpgHXVQKZ4jqkhYTi+Rr3Cg8ZHPrT7Vr/Mjl/2qiZiGa8i9MRAtRuAd8LToYZ3bhDAH1KFCLDvNjKRTFaMo25vyump58eRlIaS8ERCsgR9e8LSPbQ7FurHOX+Fk8z8BElChdt4eZ8AxXbK+2fAqPQUrfagbusvWIO4xVw8UmlrLjwgAwT/U2jgX1desWkBgmU4vVk60Zq54CAKU7UCFGXDC8iY1WueTOncytHFIJw8ARWs4zPEOBLGhLm+aQmFAJ9T/uQJZ5WG/2omtKQ01UUFRPslsvIAZR/7bcBOK0RJbhEeaeyWRgf+CaLTCLBayvLeHmCNKBOjecmVfJ6T4Abarz8SGSP5Vt28sBEJV+uOro9Y+2pRCOf8rG7GfjfjDtkf6zLVIS5sgleasx4uoHU0ONh9fzGLcbrL5eY/cSs1kNhn93AeR93arT95ScgSy0OQlCiqbPf4xQGIKi/5IoWyKBBZ1DRZ8="
        on:
          all_branches: true

    - <<: *deploy_job
      name: >-
        Publishing current (unstable) Git revision of dist to Test PyPI
        on every push to master
      env:
        PYPI_UPLOAD: true
      if: >-  # Always run, except if PR or cron
        repo == "Kuzmenko-Pavel/Prozorro-Sale-Start-Kit" AND
        branch == "main" AND
        type == "push"
      deploy:
        <<: *deploy_step
        server: https://test.pypi.org/legacy/
        user: __token__
        password:
          secure: "iACHtwlhCmRtHWv6sKKejJXVgnQumMwqzwUD6sEGcDIc9LIo1qU5aFru7Asi9i4m0lsK9yNYQi/iBLVFb8ybYAEl05EOZE3SzBOIcXdPc4a7xnn0ucJeF9iQxpoOQypsio55bl+msaxUCOKDB4XOBsABTzXh6UC/4Z21iPkuY7aEiZ9V7pDfC1bkqpUL3vbfquNpM3JAHvwQvN1siUvgK3JZ3NHhGypFNjtuzuyEnc6Ri+C991HipBNE0RnW0LBMLD8nFX+8/PYNj1iuFuJ8Wfy4smGDTN85r1RFrutPrROWd3HB5QcCCV6dxvF4V0CqF4zgrjzxw3lAGsWiFs/Ydl24DTziZvrotIHrsV9Q+SO4B2J44ZY0on99bYAKYT/1aAX3YuajOMsW8piBtc7lD6hvOf360z5kaMKd1EJLOrlsiotwczn+lGe6vGxolMubbdzsfkmXTdoXQ+Sps43dzeoJwaFDQXBj6uBNyFbi78PwP3eutZjZKqcKBLF9xjf3CwS/QfqddWoTupIuG2QsSnY4AY9ezONHftOs2MVhasr1QM1m5jT3MtbtLDgWiASGb8WzKyxt6cyBs08M7c7sW6STQFfMMDiZHBrWYfSC9mvIBuENGdkU7EAOXlHphrRFLtVwdGo4BBnEdPKyfb9ZgfJas2izEYVUHVPdHlQuxMk="
