{% raw -%}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prozorro-sale.fullname" . }}-api
  labels:
{{ include "prozorro-sale.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prozorro-sale.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
{% endraw %}