{% raw -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prozorro-sale.fullname" . }}
  labels:
{{ include "prozorro-sale.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prozorro-sale.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prozorro-sale.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-prozorro-sale-procedure-config
          configMap:
            name: {{ .Release.Name }}-prozorro-sale-procedure-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{% endraw %}
          command: [ 'python', '-m', 'prozorro_sale.{{cookiecutter.underscore_project_name}}' ]
{% raw -%}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
            initialDelaySeconds: 70
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
            initialDelaySeconds: 70
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SWAGGER_DOC
              value: "{{.Values.swaggerDoc}}"
          volumeMounts:
            - name: {{ .Release.Name }}-prozorro-sale-procedure-config
              mountPath: /config/
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{% endraw %}