include:
  - project: 'prozorro-sale/ci-build-box'
    file: '/template-ci.yml'

stages:
  - lint
  - build
  - test
  - publish
  - deploy
  - security
  - cleanup

code-style-check:
  extends: .lint-template

{%- if cookiecutter.use_helm == 'y' %}
helm-lint:
  extends: .helm-lint-template

helm-kubeval:
  extends: .helm-kubeval-template

build-helm-package:
  extends: .build-helm-package-template
  artifacts:
    paths:
      - {{cookiecutter.project_name}}-*.tgz
{%- endif %}

{%- if cookiecutter.use_docker == 'y' %}
build-new-image:
  extends: .build-new-image-template

test-integration:
  extends: .test-integration-template

test-unit:
  extends: .test-unit-template

test-safety:
  extends: .test-security-template

test-bandit:
  extends: .test-security-template
  script:
    - make bandit

publish-coverage-report:
  extends: .publish-coverage-report-template

push-image:
  extends: .push-to-registry-template

push-tagged-image:
  extends: .push-to-registry-template
  variables:
    TAG: $CI_COMMIT_REF_SLUG
  only:
    - tags

push-epic-image:
  extends: .push-to-registry-template
  variables:
    TAG: epic
  only:
    - /^epic\/.*/

{%- endif %}

{%- if cookiecutter.use_helm == 'y' %}
push-helm-package:
  extends: .push-helm-package-template
{%- endif %}

{%- if cookiecutter.use_docker == 'y' %}
cleanup-test-images:
  extends: .cleanup-test-images-template

deploy-dev:
  extends: .deploy-dev-kubernetes-template

{%- if cookiecutter.use_helm_demo == 'y' %}
# --- DEMO JOBS ---
deploy-demo:
  extends: .deploy-demo-kubernetes-template
  after_script:
    - kubectl config set-credentials prozorro.deploy --token=$RG_DEV_TOKEN
    - kubectl -n prozorro-dev apply -f demo-k8s.yaml
    - kubectl -n prozorro-dev rollout restart deployment prozorro-dev-{{cookiecutter.project_name}}-demo
{%- endif %}
{%- endif %}