apiVersion: v1
kind: Service
metadata:
  name: prozorro-dev-{{cookiecutter.project_name}}-demo
  labels:
    app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
    app.kubernetes.io/instance: prozorro-dev
    app.kubernetes.io/version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
    app.kubernetes.io/instance: prozorro-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prozorro-dev-{{cookiecutter.project_name}}-demo
  labels:
    app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
    app.kubernetes.io/instance: prozorro-dev
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
      app.kubernetes.io/instance: prozorro-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
        app.kubernetes.io/instance: prozorro-dev
    spec:
      imagePullSecrets:
        - name: registry-gitlab
      volumes:
        - name: procedure-config
          configMap:
            name: prozorro-dev-procedure-config

      containers:
        - name: {{cookiecutter.project_name}}-demo
          image: "registry-gitlab.prozorro.sale/prozorro-sale/{{cookiecutter.gitlab_project_name}}:demo"
          imagePullPolicy: Always
          command: [ 'python', '-m', 'prozorro_sale.{{cookiecutter.project_name | to_snake}}.api' ]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: http
          readinessProbe:
            httpGet:
              path: /api/ping
              port: http
          resources:
            limits:
              cpu: 1200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: SWAGGER_DOC
              value: '1'
          volumeMounts:
            - name: procedure-config
              mountPath: /config/



---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prozorro-dev-{{cookiecutter.project_name}}-demo
  labels:
    app.kubernetes.io/name: {{cookiecutter.project_name}}-demo
    app.kubernetes.io/instance: prozorro-dev
    app.kubernetes.io/version: "1.0"


spec:
  rules:
    - host: "{{cookiecutter.project_name}}-demo-dev.prozorro.sale"
      http:
        paths:
          - path: /
            backend:
              serviceName: prozorro-dev-{{cookiecutter.project_name}}-demo
              servicePort: http
