version: '3.9'

services:
  {{cookiecutter.project_name}}-app: &base_app
    image: "${IMAGE}"
    container_name: {{cookiecutter.project_name}}-api
    command: python -m prozorro_sale.{{cookiecutter.project_name | to_snake}}.api
    environment:
      SWAGGER_DOC: 1

  {{cookiecutter.project_name}}-databridge:
    <<: *base_app
    container_name: {{cookiecutter.project_name}}-databridge
    command: python -m prozorro_sale.{{cookiecutter.project_name | to_snake}}.databridge

  {{cookiecutter.project_name}}-test-integration: &test_app
    <<: *base_app
    image: "${IMAGE_TEST}"
    container_name: {{cookiecutter.project_name}}-test-integration
    environment:
      SWAGGER_DOC: 0

  {{cookiecutter.project_name}}-test-unit:
    <<: *test_app
    container_name: {{cookiecutter.project_name}}-test-unit

  {{cookiecutter.project_name}}-local: &local_app
    <<: *base_app
    tty: true
    command: adev runserver prozorro_sale/{{cookiecutter.project_name | to_snake}}/api
    environment: &local_app_environment
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      PYTHONASYNCIODEBUG: 1
      AIO_PORT: 8080
      AIO_DEBUG_TOOLBAR: 1
      AIO_LIVERELOAD: 1
    volumes:
      - ./src:/{{cookiecutter.project_name}}:delegated
    restart: always
    ports:
      - 8080:8080

  {{cookiecutter.project_name}}-databridge-local:
    <<: *local_app
    container_name: {{cookiecutter.project_name}}-databridge
    command: adev runserver --app-factory=create_databridge prozorro_sale/{{cookiecutter.project_name | to_snake}}/databridge
    environment:
      <<: *local_app_environment
      AIO_PORT: 8081
    ports:
      - 8081:8081