{% raw -%}
{{- $Context := dict "ArchitectComponent" "api" "Release" .Release "Chart" .Chart "Values" .Values.application.api  "Global" . -}}
{{- include "prozorro-helm-template.base-http-app" $Context -}}
{% endraw %}