logging:
  version: 1
  disable_existing_loggers: False
  root:
    level: INFO
    handlers:
      - console
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
      filters:
        - requestid
        - procedureid
  filters:
    requestid: {}
    procedureid: {}
  formatters:
    default:
      class: 'prozorro_sale.tools.logger.LogFormatter'
      format: '[%(asctime)s.%(msecs)03dZ] | %(name)s | %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S'
